"""fix: ensure users table not dropped

Revision ID: 7b03bdad456c
Revises: fbfd0e74ee67
Create Date: 2025-08-20 03:38:22.645438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b03bdad456c'
down_revision: Union[str, Sequence[str], None] = 'fbfd0e74ee67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # no-op: users table already exists; ensure not dropped by previous migration
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
