version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "abdulrhmanasami"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
