repos:
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.18.4
  hooks:
  - id: gitleaks
- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
  - id: black
    language_version: python3
