services:
  backend:
    build:
      context: ..
      dockerfile: apps/backend/Dockerfile
    environment:
      - PORT=8000
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=eurodropship
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "${PORT:-8800}:8000"
    depends_on:
      - db
    profiles: ["with-backend"]
