name: CI
on:
  pull_request:
  push: { branches: [ main, master ] }
jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/backend
    services:
      postgres:
        image: postgres:16
        env: { POSTGRES_PASSWORD: postgres, POSTGRES_DB: shoobydo }
        ports: [ "5546:5432" ]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s --health-timeout=5s --health-retries=10
      redis:
        image: redis:7
        ports: [ "6389:6379" ]
    env:
      POSTGRES_PORT: 5546
      REDIS_PORT: 6389
      SHOOBYDO_BACKEND_PORT: 8811
      SECRET_KEY: ci-dummy-secret-key
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: apps/backend/.venv
          key: ${{ runner.os }}-pip-${{ hashFiles('apps/backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install deps
        run: |
          python -m venv .venv && . .venv/bin/activate
          pip install -r requirements.txt pytest httpx
      - name: Migrate + run API
        run: |
          . .venv/bin/activate
          alembic upgrade heads || alembic upgrade head
          nohup uvicorn app.main:app --host 0.0.0.0 --port $SHOOBYDO_BACKEND_PORT >/tmp/api.log 2>&1 &
          for i in {1..30}; do curl -sf "http://127.0.0.1:${SHOOBYDO_BACKEND_PORT}/health" && break || sleep 1; done
      - name: Run tests
        run: |
          . .venv/bin/activate
          pytest -q

  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install deps
        working-directory: apps/frontend
        run: |
          npm ci || npm install
      - name: Lint
        working-directory: apps/frontend
        run: |
          npx next lint || echo "Skipping lint failures for now"

  docker-build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build backend image
        run: docker build -t backend-ci:latest apps/backend

