name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r apps/backend/requirements.txt
      - run: pip install pytest pytest-asyncio pytest-cov ruff
      - working-directory: apps/backend
        run: pytest -q --maxfail=1 --disable-warnings --cov=apps/backend/app --cov-report=term-missing --cov-fail-under=75
      - run: ruff check apps/backend/app
